application: gdn-feedback
version: 6
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  secure: always
  static_dir: static
- url: /admin/.*
  script: admin.app
  login: admin
  secure: always
- url: /
  script: app.app
  secure: always
- url: /.*
  login: required
  secure: always
  script: app.app

libraries:
- name: jinja2
  version: latest